import "server-only";
import { getPayload } from "payload";
import config from "@payload-config";
import { getCapabilities, getHero, getHomeSections, getProcess } from "./cms";
import { processSteps as seedProcessSteps } from "@/content/site";
import { processStepsAr } from "@/content/ar";
import { getLocale } from "./getLocale";
import { getUI, type Locale } from "./i18n";
import { LOCALIZED_TEXT_FIELDS, type HomeSection, type MediaRef } from "./homeBlocks";

/**
 * Home page data layer for the Visual Editor and the front end.
 *
 * Sections live in the `home-page` global as a blocks array. Until the first
 * save, defaults are assembled from the legacy home-* globals / seed content,
 * so the site looks identical before and after migrating.
 *
 * Everything here works on the FLAT section shape from homeBlocks.ts:
 * { id, type, hidden, ...fields } with upload fields as { id, url } refs.
 */

export type HomePageData = { sections: HomeSection[]; source: "global" | "default" };

/* ------------------------------ normalization ----------------------------- */

type AnyObj = Record<string, unknown>;

const MEDIA_FIELDS = new Set(["posterImage", "image"]);

function mediaRef(v: unknown, size: string): MediaRef {
  if (!v) return null;
  if (typeof v === "number" || typeof v === "string") return { id: v };
  const m = v as { id?: number | string; url?: string | null; sizes?: Record<string, { url?: string | null } | undefined> };
  return { id: m.id, url: m.sizes?.[size]?.url || m.url || undefined };
}

function normalizeValue(key: string, value: unknown): unknown {
  if (MEDIA_FIELDS.has(key)) return mediaRef(value, key === "posterImage" ? "wide" : "card");
  if (Array.isArray(value)) {
    return value.map((row) => (row && typeof row === "object" ? normalizeObj(row as AnyObj) : row));
  }
  if (value && typeof value === "object") return normalizeObj(value as AnyObj);
  return value;
}

function normalizeObj(obj: AnyObj): AnyObj {
  const out: AnyObj = {};
  for (const [k, v] of Object.entries(obj)) out[k] = normalizeValue(k, v);
  return out;
}

type BlockRow = AnyObj & { id?: string; blockType: string; hidden?: boolean };

function normalizeSections(rows: BlockRow[]): HomeSection[] {
  return rows.map((row) => {
    const { id, blockType, ...rest } = row;
    delete (rest as AnyObj).blockName;
    return { id, type: blockType, ...normalizeObj(rest) } as HomeSection;
  });
}

/* ------------------------------ serialization ----------------------------- */

/** Row ids generated by the editor for not-yet-saved rows are stripped so Payload assigns real ones. */
const cleanId = (id: unknown): string | undefined =>
  typeof id === "string" && id && !id.startsWith("default-") && !id.startsWith("new-") ? id : undefined;

function serializeValue(key: string, value: unknown): unknown {
  if (MEDIA_FIELDS.has(key)) return (value as MediaRef)?.id ?? null;
  if (Array.isArray(value)) {
    return value.map((row) => {
      if (!row || typeof row !== "object") return row;
      const { id, ...rest } = row as AnyObj;
      const cid = cleanId(id);
      return { ...(cid ? { id: cid } : {}), ...serializeObj(rest) };
    });
  }
  if (value && typeof value === "object") return serializeObj(value as AnyObj);
  return value;
}

function serializeObj(obj: AnyObj): AnyObj {
  const out: AnyObj = {};
  for (const [k, v] of Object.entries(obj)) out[k] = serializeValue(k, v);
  return out;
}

export function serializeSections(sections: HomeSection[]): AnyObj[] {
  return sections.map((s) => {
    const { id, type, ...rest } = s;
    const cid = cleanId(id);
    return { ...(cid ? { id: cid } : {}), blockType: type, ...serializeObj(rest) };
  });
}

/* --------------------------- defaults (migration) -------------------------- */

/** Builds the current home page as sections from the legacy globals / seed content. */
export async function buildDefaultSections(locale: Locale): Promise<HomeSection[]> {
  const [hero, capabilities, hs, process] = await Promise.all([
    getHero(locale),
    getCapabilities(locale),
    getHomeSections(locale),
    getProcess(locale),
  ]);
  const contact = getUI(locale).pages.home.contact;
  const steps = process.steps
    .filter((s) => s.title || s.description)
    .map((s) => ({ title: s.title ?? "", description: s.description ?? "" }));
  // Legacy rows can be empty after the bilingual migration — fall back to seed steps.
  const safeSteps = steps.length ? steps : (locale === "ar" ? processStepsAr : seedProcessSteps).map((s) => ({ title: s.title, description: s.description }));

  return [
    {
      id: "default-hero",
      type: "hero",
      badge: hero.badge,
      headline: hero.headline,
      highlight: hero.highlight,
      subheading: hero.subheading,
      primaryCta: hero.primaryCta,
      secondaryCta: hero.secondaryCta,
      posterImage: null,
      posterImageUrl: hero.posterImage ?? "",
      backgroundVideoUrl: hero.backgroundVideoUrl ?? "",
      showStats: hero.showStats,
      stats: hero.stats.filter((s) => s.value || s.label).map((s) => ({ value: s.value ?? "", label: s.label ?? "" })),
    },
    {
      id: "default-capabilities",
      type: "capabilities",
      eyebrow: capabilities.eyebrow,
      items: capabilities.items.map((it) => ({
        image: null,
        imageUrl: it.image,
        eyebrow: it.eyebrow,
        title: it.title,
        text: it.text,
        href: it.href,
      })),
    },
    { id: "default-services", type: "services", ...hs.services },
    {
      id: "default-process",
      type: "process",
      eyebrow: process.eyebrow,
      title: process.heading,
      description: process.description,
      steps: safeSteps,
    },
    { id: "default-case-studies", type: "caseStudies", ...hs.caseStudies },
    { id: "default-showcase", type: "showcase", ...hs.selectedWork },
    { id: "default-team", type: "team", ...hs.team },
    {
      id: "default-cta",
      type: "cta",
      title: hs.cta.title,
      description: hs.cta.description,
      buttonLabel: hs.cta.buttonLabel,
      buttonHref: hs.cta.buttonHref,
    },
    {
      id: "default-contact",
      type: "contact",
      eyebrow: contact.eyebrow,
      title: contact.title,
      description: contact.description,
    },
  ];
}

/* --------------------------------- loading -------------------------------- */

export async function loadHomeSections(locale: Locale): Promise<HomePageData> {
  try {
    const payload = await getPayload({ config });
    const g = (await payload.findGlobal({ slug: "home-page" as never, locale, depth: 1 })) as AnyObj | null;
    const rows = (g?.sections as BlockRow[]) || [];
    if (rows.length) return { sections: normalizeSections(rows), source: "global" };
  } catch {
    // CMS unreachable — fall through to defaults.
  }
  return { sections: await buildDefaultSections(locale), source: "default" };
}

/** Front-end entry: sections for the current request's locale. */
export async function getHomePage(): Promise<HomePageData> {
  return loadHomeSections(await getLocale());
}

/* --------------------------------- saving --------------------------------- */

/** Shared with the editor: which block fields are stored per language. */
const LOCALIZED_FIELDS = LOCALIZED_TEXT_FIELDS;

function mergeLocalized(saved: unknown, defaults: unknown): unknown {
  if (Array.isArray(saved) && Array.isArray(defaults)) {
    return saved.map((row, i) => mergeLocalized(row, defaults[i]));
  }
  if (saved && defaults && typeof saved === "object" && typeof defaults === "object" && !Array.isArray(saved)) {
    const out: AnyObj = { ...(saved as AnyObj) };
    for (const [k, dv] of Object.entries(defaults as AnyObj)) {
      if (LOCALIZED_FIELDS.has(k) && (typeof dv === "string" || dv == null)) out[k] = dv ?? "";
      else if (k in out) out[k] = mergeLocalized(out[k], dv);
    }
    return out;
  }
  return saved;
}

export async function saveHomeSections(sections: HomeSection[], locale: Locale): Promise<void> {
  const payload = await getPayload({ config });
  const before = (await payload.findGlobal({ slug: "home-page" as never, locale, depth: 0 })) as AnyObj | null;
  const wasEmpty = !((before?.sections as unknown[]) || []).length;

  await payload.updateGlobal({
    slug: "home-page" as never,
    locale,
    data: { sections: serializeSections(sections) } as never,
  });

  if (!wasEmpty) return;

  // First save: the other locale would otherwise be empty and fall back to this
  // locale's text. Backfill it with that locale's defaults (same content the
  // site was already showing) so both languages keep their own words.
  const other: Locale = locale === "ar" ? "en" : "ar";
  try {
    const [saved, otherDefaults] = await Promise.all([
      payload.findGlobal({ slug: "home-page" as never, locale: other, depth: 1 }) as Promise<AnyObj | null>,
      buildDefaultSections(other),
    ]);
    const savedSections = normalizeSections(((saved?.sections as BlockRow[]) || []));
    const merged = savedSections.map((s, i) => {
      const def = otherDefaults[i];
      if (!def || def.type !== s.type) return s; // structure changed pre-save — keep fallback text
      return mergeLocalized(s, def) as HomeSection;
    });
    await payload.updateGlobal({
      slug: "home-page" as never,
      locale: other,
      data: { sections: serializeSections(merged) } as never,
    });
  } catch {
    // Backfill is best-effort; the primary save already succeeded.
  }
}
